backend:
  name: git-gateway
  branch: main

media_folder: "static/img"

collections:
  - name: "posts"
    label: "Postt" 
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date", format: "YYYY-MM-DD" }      
      - { label: "External Link", name: "externalLink", widget: "string" }      
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }  